# **NUMPY**

---



#### Importing Numpy

In [2]:
import numpy as np
import math

In [3]:
a=np.array([1,2,3])
print(a)
print(a.ndim) #Dimension
print(a.dtype) #DataType of the element

[1 2 3]
1
int64


In [4]:
b=np.array([[1,2,3],[31,45,5]])
b.shape #Shape of the numpy array

(2, 3)

In [5]:
b.dtype

dtype('int64')

In [8]:
c=np.array([[2.5,3,5.9],[1.4,3.5,5]])
c.dtype.name

'float64'

- `np.random.rand()` → uniform distribution between 0 and 1.
- `np.random.randn()` → normal distribution with mean 0 and standard deviation 1.

- `np.zeros(2,3)`=> Create an numpy array of dimension (2,3) filled with element=0
- `np.ones(2,3)`=> Create an numpy array of dimension (2,3) filled with element=1
- `np.random.rand(2,3)` => Create an numpy array of dimension (2,3) filled with random element range=(0,1)
- `np.arange(1,12,2)` => Create an numpy array contaning consecutive element with gap 2.dim=1
- `np.linspace(0,2,15)` =>Declares float sequence of array using LINSPACE

In [9]:
d=np.zeros((2,3))
e=np.ones((2,3))
print(d)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
np.random.rand(2,3)

array([[0.99711023, 0.39896937, 0.84880775],
       [0.77921734, 0.14905916, 0.54616871]])

In [ ]:
f=np.arange(1,12,2)
f

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

#### Addition,Product
- `a+b` => Addition of two array
- `a*b` =>Element wise product of two array
- `a>1` => Outputs boolean array of same dim based on the condyion imposed on element (a>1)
- `a@b` => MATRIX PRODUCT(@)

In [13]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a*b)

[ 6  8 10 12]
[ 5 12 21 32]


In [14]:
a>1

array([False,  True,  True,  True])

In [15]:
b%2==0

array([False,  True, False,  True])

In [16]:
c=np.array([[1,1],[0,1]])
d=np.array([[2,0],[3,4]])
print(c@d)

[[5 4]
 [3 4]]


In [18]:
e=np.array([1,2,3,4])
f=np.array([2.2,3.3,4.2,1.1])
print(e.dtype)
print(f.dtype)
g=e+f
print(g.dtype) #UPCASTING TO FLOAT

int64
float64
float64


#### Different aggregate function imposing on vector

In [19]:
print(g.sum())
print(g.max())
print(g.min())
print(g.mean())

20.799999999999997
7.2
3.2
5.199999999999999


- `np.arange(1,17).reshape(2,8)` : Converts the 1d array into dim(2,8)

In [20]:
h=np.arange(1,17).reshape(2,8)
h

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

#### INDEXING

In [26]:
a=np.array([[1,2,7,8],
           [3,4,6,9],
           [5,6,0,1]])
b=np.array([a[0,0],a[1,1],a[2,1]])
print(b)

[1 4 6]


In [24]:
b=np.array(a[[0,1,2],[0,1,1]])#zipping
print(b)

[1 4 6]


In [25]:
print(a[a>5])

[7 8 6 9 6]


- `a[:2]` selects rows from index 0 to 1 (i.e., rows 0 and 1):
- `a[:2,1:]` selects rows from index 0 to 1 and column from 1  to end
- remember that slicing in array is view of the same data, so change in value cause the change in value in the original array

In [27]:
print(a[:1])
print(a[:2,1:])

[[1 2 7 8]]
[[2 7 8]
 [4 6 9]]


In [ ]:
#remember that slicing in array is view of the same data
# so change in value cause the change in value in the original array
b=a[:2,1:2]
print('before changing',b)
b[0,0]=50
print('after changing',b)
print(a)

before changing [[2]
 [4]]
after changing [[50]
 [ 4]]
[[ 1 50  7  8]
 [ 3  4  6  9]
 [ 5  6  0  1]]


In [ ]:
book=np.genfromtxt('Book1.csv',skip_header=1,delimiter=',')
book

array([[1.000e+00, 2.000e+01, 6.000e+00, 2.008e+03, 0.000e+00, 1.000e+00],
       [2.000e+00, 3.000e+01, 8.000e+00, 2.007e+03, 1.000e+00, 0.000e+00],
       [3.000e+00, 3.200e+01, 7.000e+00, 2.008e+03, 8.000e+00, 9.000e+00],
       [4.000e+00, 4.000e+00, 1.000e+00, 2.009e+03, 4.000e+00, 5.000e+00],
       [5.000e+00, 1.500e+01, 9.000e+00, 2.008e+03, 4.000e+00, 6.000e+00],
       [6.000e+00, 4.500e+01, 2.000e+01, 2.004e+03, 4.500e+01, 6.000e+00]])

In [ ]:
print(book[:,0])
print(book[:,0:1])               #**DIFFERENCE**

[1. 2. 3. 4. 5. 6.]
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]


`book[:,[1,3,4]]` : It selects all the row and 1,3,4 col

In [ ]:
print(book[:,[1,3,4]])            #nonconsecutive column

[[2.000e+01 2.008e+03 0.000e+00]
 [3.000e+01 2.007e+03 1.000e+00]
 [3.200e+01 2.008e+03 8.000e+00]
 [4.000e+00 2.009e+03 4.000e+00]
 [1.500e+01 2.008e+03 4.000e+00]
 [4.500e+01 2.004e+03 4.500e+01]]


In [ ]:
print(book[:,-1].mean())    #SELECTING THE LAST COLUMN

4.5


#### Converting two dimensional list to onedimesional list which contains tuples

In [ ]:
book2=np.genfromtxt('Book1.csv',dtype=None,delimiter=',',skip_header=1,
                    names=('entries','cty','cyl','year','a','b'))
print(book2)
book2.shape                         #It is onedimensional array of 6 tuples"


[(1, 20,  6, 2008,  0, 1) (2, 30,  8, 2007,  1, 0)
 (3, 32,  7, 2008,  8, 9) (4,  4,  1, 2009,  4, 5)
 (5, 15,  9, 2008,  4, 6) (6, 45, 20, 2004, 45, 6)]


(6,)

In [ ]:
book2['a'][0:5]

array([0, 1, 8, 4, 4])

In [ ]:
book2['a']=book2['a']/4
book2['a']

array([0, 0, 0, 0, 0, 2])

In [ ]:
len(book2[book2['a']==49])

0

In [28]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [29]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])